---
sidebar: sidebar 
permalink: task-discovering-ontap.html 
keywords: ontap, cluster, discover, manage, discovering, fas, aff, discover onprem, discover aff cluster, discover cluster, add cluster, active iq, digital wallet 
summary: Scopri i cluster ONTAP on-premise di BlueXP per iniziare a gestire i volumi ed eseguire una gestione avanzata utilizzando Gestione di sistema di ONTAP, disponibile da BlueXP. 
---
= Scopri i cluster ONTAP on-premise
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Scopri i cluster ONTAP on-premise di BlueXP per iniziare a gestire i volumi ed eseguire una gestione avanzata utilizzando Gestione di sistema di ONTAP, disponibile da BlueXP.



== Opzioni di rilevamento e gestione

BlueXP offre due modi per rilevare e gestire i cluster ONTAP on-premise:

Rilevamento attraverso un connettore:: Questa opzione consente di gestire i cluster che eseguono ONTAP 8.3 e versioni successive utilizzando le seguenti funzionalità:
+
--
* La vista Standard, che fornisce le operazioni di base del volume
* La visualizzazione avanzata, che consente la gestione tramite Gestione di sistema (supportata con ONTAP 9.10.0 e versioni successive)
* Integrazione con i servizi BlueXP, che offrono replica dei dati, backup e ripristino, classificazione dei dati e tiering dei dati


Questa opzione richiede un connettore, che è possibile installare in un cloud provider o on-premise.

--
Rilevamento diretto:: Questa opzione consente di gestire i cluster che eseguono ONTAP 9.12.1 e versioni successive utilizzando Gestione sistema. Non sono disponibili altre opzioni di gestione. Non è possibile utilizzare la vista Standard e non è possibile attivare i servizi dati.
+
--
Questa opzione non richiede un connettore.

Quando si accede a Gestore di sistema su un cluster ONTAP on-premise con 9.12.1 o versione successiva e con connettività al servizio BlueXP, viene richiesto di gestire il cluster direttamente da BlueXP. Se si segue questa richiesta, il cluster viene rilevato in BlueXP utilizzando l'opzione di rilevamento diretto.

--


Una volta scoperto, i cluster sono disponibili come ambiente di lavoro su BlueXP Canvas.

Se si decide di utilizzare l'altra opzione di rilevamento in un secondo momento, sarà necessario rilevare il cluster on-premise come ambiente di lavoro separato in Canvas. È quindi possibile rimuovere l'altro ambiente di lavoro.



== Requisiti

Prima di scoprire il cluster ONTAP on-premise, assicurarsi di aver soddisfatto i seguenti requisiti.



=== Requisiti generali

* Dovresti aver iniziato a utilizzare BlueXP, che include l'accesso e la configurazione di un account.
+
https://docs.netapp.com/us-en/cloud-manager-setup-admin/concept-overview.html["Scopri come iniziare a utilizzare BlueXP"^]

* Sono necessari l'indirizzo IP di gestione del cluster e la password per l'account utente admin.
* BlueXP rileva i cluster ONTAP utilizzando HTTPS. Se si utilizzano criteri firewall personalizzati, il cluster ONTAP deve consentire l'accesso HTTPS in entrata attraverso la porta 443.
+
Il criterio firewall predefinito "mgmt" consente l'accesso HTTPS in entrata da tutti gli indirizzi IP. Se questo criterio predefinito è stato modificato o se è stato creato un criterio firewall personalizzato, è necessario associare il protocollo HTTPS a tale criterio e abilitare l'accesso dall'host del connettore.





=== Requisiti per il rilevamento e la gestione dei connettori

* Il cluster on-premise deve eseguire ONTAP 8.3 o versione successiva.
* Un connettore deve essere installato in un cloud provider o on-premise.
+
Se si desidera eseguire il tiering dei dati cold nel cloud, è necessario esaminare i requisiti per il connettore in base alla posizione in cui si prevede di eseguire il tiering dei dati cold.

+
** https://docs.netapp.com/us-en/cloud-manager-setup-admin/concept-connectors.html["Scopri di più sui connettori"^]
** https://docs.netapp.com/us-en/cloud-manager-setup-admin/task-managing-connectors.html["Passaggio da un connettore all'altro"^]
** https://docs.netapp.com/us-en/cloud-manager-tiering/concept-cloud-tiering.html["Scopri di più sul tiering BlueXP"^]


* L'host del connettore deve consentire l'accesso HTTPS in uscita attraverso la porta 443.
+
Se il connettore si trova nel cloud, tutte le comunicazioni in uscita sono consentite dal gruppo di sicurezza predefinito.





=== Requisiti per il rilevamento e la gestione diretti

* Il cluster on-premise deve eseguire ONTAP 9.12.1 o versione successiva.
* Il cluster deve disporre di connettività in entrata e in uscita al servizio BlueXP:
+
https://cloudmanager.cloud.netapp.com/ontap-service/check-service-connection

* Il computer utilizzato per accedere alla console BlueXP deve disporre di una connessione di rete al cluster ONTAP on-premise, simile a quella utilizzata per fornire connessioni ad altre risorse della rete privata.




== Scopri i cluster

Scopri i tuoi cluster ONTAP on-premise da Canvas in BlueXP. Quando si avvia il processo di rilevamento, BlueXP rileva il cluster come segue:

* Se si dispone di un connettore attivo che dispone di una connessione al cluster ONTAP, BlueXP utilizzerà tale connettore per rilevare e gestire il cluster.
* Se non si dispone di un connettore o se il connettore non dispone di una connessione al cluster ONTAP, BlueXP utilizzerà automaticamente l'opzione di rilevamento e gestione diretta.


.Fasi
. Dal menu di navigazione, selezionare *Storage > Canvas*.
. Nella pagina Canvas, fare clic su *Add Working Environment* (Aggiungi ambiente di lavoro) e selezionare *on-premise*.
. Accanto a on-premise ONTAP, selezionare *Discover*.
. Nella pagina _Discover_, inserire l'indirizzo IP di gestione del cluster e la password per l'account utente admin.
. Se si rileva direttamente il cluster (senza un connettore), selezionare *Save the credentials* (Salva le credenziali).
+
Se si seleziona questa opzione, non sarà necessario immettere nuovamente le credenziali ogni volta che si apre l'ambiente di lavoro. Queste credenziali sono associate solo all'utente BlueXP. Non vengono salvati per l'utilizzo da parte di altri utenti nel tuo account.

. Selezionare *Discover*.


.Risultato
BlueXP rileva il cluster e lo aggiunge come ambiente di lavoro su Canvas. È ora possibile iniziare a gestire il cluster.

* link:task-manage-ontap-direct.html["Scopri come gestire i cluster rilevati direttamente"]
* link:task-manage-ontap-connector.html["Scopri come gestire i cluster rilevati con un connettore"]

